version: '3.6'
services:
  janusgw:
    container_name: 'janusgw'

    build:
      context: .
      dockerfile: Dockerfile.final
    ports:
      # - "80:80"
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "8089:8089"
      - "10000-10200:10000-10200/udp"
    environment:
      - DOCKER_IP=192.168.2.103
    volumes:
      - janus_static:/usr/local/src/janus-gateway/html
      # - ./config/janus:/opt/janus/etc/janus
    networks:
      - youbook_network


volumes:
  janus_static:

networks:
  youbook_network:
    driver: bridge
