version: '2'
services:
  nginx:
    container_name: 'nginx'
    build:
      context: ./config/nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./config/nginx/:/etc/nginx/:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - janus_static:/usr/share/janus/html/


    networks:
      - youbook_network
    # depends_on:

  janusgw:
    container_name: 'janusgw'
    build: ./
    ports:
      # - "80:80"
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "8089:8089"
      - "7889:7889"
      - "10000-10200:10000-10200/udp"
    volumes:
      # - ./config/janusx:/usr/local/etc/janus
      - janus_static:/usr/local/src/janus-gateway/html
    networks:
      - youbook_network


volumes:
  janus_static:

networks:
  youbook_network:
    driver: bridge
