version: '2'
services:
  nginx:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d/
      - janus_static:/root/janus-gateway/html/
      - /etc/letsencrypt:/etc/letsencrypt:ro

    networks:
      - youbook_network
    # depends_on:

  janusgw:
    container_name: 'janusgw'
    build: ./
    ports:
      # - "80:80"
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "8089:8089"
      - "10000-10200:10000-10200/udp"
    environment:
      - DOCKER_IP=192.168.2.103
    volumes:
      - janus_static:/usr/local/src/janus-gateway/html
    networks:
      - youbook_network


volumes:
  janus_static:

networks:
  youbook_network:
    driver: bridge
